### ISSUE TITLE
Move libpaq/ttl2c To Its Own Project(s)

### ISSUE THREAD

**Issue by bkedev** [lvtk/lvtk#14]
This will be part of removing things that aren't implementing LV2 boilerplate code.
 - Plugin examples at this point should probably not rely on ttl2c for header generation.
 - libpaq should either be renamed and released with the new name, or continue to be compiled in with ttl2c. The reason here is debian proper already has libpaq-dev (from lv2-c++-tools)

**Comment by SpotlightKid** [comment]
I'm the mainter of the Arch Linux 'lvtk-git' package.

I noticed that during the build, the waf script also might use the `ttl2c` program which is already installed on the system. This broke my last built, because `ttl2c` was linked to `libboost_system.so.1.59.0` but my system had already upgraded to `libboost_system.so.1.60.0` so calling the system `ttl2c` failed.

The build process should probably use a relative path to call `ttl2c`.

**Comment by SpotlightKid** [comment]
Ah, sorry, I now see that `ttl2c` has already been moved to a separate project. Ok, I'll have too create an AUR package for `ttl2c` then.

**Comment by mfisher31** [comment]
No biggie.  The ```ttl2c``` project might have linker errors with ```libboost_system``` as lvtk itself did (does).  If you by chance discover issues while making the AUR package, by all means create an issue.

**Comment by SpotlightKid** [comment]
Yes, as with lvtk, I have to do `export LDFLAGS="-lboost_system"` before make to make ttl2c compile.

**Comment by mfisher31** [comment]
@SpotlightKid Checkout the latest ttl2c, https://github.com/lvtk/ttl2c/commit/d832ab87b13b17d495fe5bb9d67b0d87cb661670

The libboost_system linker problem should resolved
